version: '3.4'

services:
  formsdb:
    container_name: formsdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  form.api:
    container_name: form.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://formsdb:27017"
    depends_on:
      - formsdb 
    ports:
      - "8555:80"
